"""align p3 schema to plan

Revision ID: 3caa35db2988
Revises: 57c5f4a595c1
Create Date: 2026-05-28 13:56:22.955640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3caa35db2988'
down_revision = '57c5f4a595c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('mastery_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['placement_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', name='uq_placement_result_paper')
    )
    op.create_table('placement_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['placement_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'student_user_id', name='uq_placement_submission_paper_student')
    )
    op.create_table('placement_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['placement_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['placement_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_placement_answer_submission_question')
    )
    op.add_column('daily_tasks', sa.Column('est_minutes', sa.Integer(), nullable=False))
    op.add_column('daily_tasks', sa.Column('title', sa.String(length=240), nullable=False))
    op.add_column('master_plan_versions', sa.Column('source', sa.String(length=40), nullable=False))
    op.add_column('master_plan_versions', sa.Column('weekly_goals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('master_plan_versions', sa.Column('daily_time_budget_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('master_plan_versions', 'phases_json')
    op.add_column('master_plans', sa.Column('status', sa.String(length=40), nullable=False))
    op.add_column('master_plans', sa.Column('current_version_id', sa.UUID(), nullable=True))
    op.drop_column('master_plans', 'weekly_goals_json')
    op.drop_column('master_plans', 'daily_time_budget_json')
    op.add_column('mastery_snapshots', sa.Column('version', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_mastery_snapshot_student_subject_version', 'mastery_snapshots', ['student_user_id', 'subject_code', 'version'])
    op.drop_column('mastery_snapshots', 'as_of_date')
    op.add_column('placement_papers', sa.Column('student_user_id', sa.UUID(), nullable=False))
    op.add_column('placement_papers', sa.Column('status', sa.String(length=40), nullable=False))
    op.create_foreign_key(None, 'placement_papers', 'users', ['student_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('placement_papers', 'title')
    op.add_column('placement_questions', sa.Column('knowledge_node_id', sa.UUID(), nullable=True))
    op.add_column('placement_questions', sa.Column('q_type', sa.String(length=40), nullable=False))
    op.add_column('placement_questions', sa.Column('stem', sa.String(), nullable=False))
    op.add_column('placement_questions', sa.Column('answer_key', sa.String(length=40), nullable=False))
    op.add_column('placement_questions', sa.Column('points', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'placement_questions', 'syllabus_nodes', ['knowledge_node_id'], ['id'], ondelete='SET NULL')
    op.drop_column('placement_questions', 'answer_json')
    op.drop_column('placement_questions', 'prompt')
    op.add_column('subject_plan_versions', sa.Column('source', sa.String(length=40), nullable=False))
    op.drop_column('subject_plan_versions', 'weekly_goals_json')
    op.add_column('subject_plans', sa.Column('current_version_id', sa.UUID(), nullable=True))
    op.add_column('syllabus_nodes', sa.Column('name', sa.String(length=240), nullable=False))
    op.add_column('syllabus_nodes', sa.Column('weight', sa.Integer(), nullable=False))
    op.drop_column('syllabus_nodes', 'code')
    op.drop_column('syllabus_nodes', 'meta_json')
    op.drop_column('syllabus_nodes', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('syllabus_nodes', sa.Column('title', sa.VARCHAR(length=240), autoincrement=False, nullable=False))
    op.add_column('syllabus_nodes', sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('syllabus_nodes', sa.Column('code', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('syllabus_nodes', 'weight')
    op.drop_column('syllabus_nodes', 'name')
    op.drop_column('subject_plans', 'current_version_id')
    op.add_column('subject_plan_versions', sa.Column('weekly_goals_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('subject_plan_versions', 'source')
    op.add_column('placement_questions', sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('placement_questions', sa.Column('answer_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'placement_questions', type_='foreignkey')
    op.drop_column('placement_questions', 'points')
    op.drop_column('placement_questions', 'answer_key')
    op.drop_column('placement_questions', 'stem')
    op.drop_column('placement_questions', 'q_type')
    op.drop_column('placement_questions', 'knowledge_node_id')
    op.add_column('placement_papers', sa.Column('title', sa.VARCHAR(length=240), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'placement_papers', type_='foreignkey')
    op.drop_column('placement_papers', 'status')
    op.drop_column('placement_papers', 'student_user_id')
    op.add_column('mastery_snapshots', sa.Column('as_of_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_mastery_snapshot_student_subject_version', 'mastery_snapshots', type_='unique')
    op.drop_column('mastery_snapshots', 'version')
    op.add_column('master_plans', sa.Column('daily_time_budget_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('master_plans', sa.Column('weekly_goals_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('master_plans', 'current_version_id')
    op.drop_column('master_plans', 'status')
    op.add_column('master_plan_versions', sa.Column('phases_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('master_plan_versions', 'daily_time_budget_json')
    op.drop_column('master_plan_versions', 'weekly_goals_json')
    op.drop_column('master_plan_versions', 'source')
    op.drop_column('daily_tasks', 'title')
    op.drop_column('daily_tasks', 'est_minutes')
    op.drop_table('placement_answers')
    op.drop_table('placement_submissions')
    op.drop_table('placement_results')
    # ### end Alembic commands ###
