"""add p4 self tests and wrong book

Revision ID: 5c835f8f2ee8
Revises: 15c768af9282
Create Date: 2026-05-28 17:06:32.277672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5c835f8f2ee8'
down_revision = '15c768af9282'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_test_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('subject_code', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wrong_book_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('subject_code', sa.String(length=40), nullable=False),
    sa.Column('knowledge_node_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('question_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['syllabus_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_test_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('knowledge_node_id', sa.UUID(), nullable=True),
    sa.Column('q_type', sa.String(length=40), nullable=False),
    sa.Column('stem', sa.String(), nullable=False),
    sa.Column('choices_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_key', sa.String(length=2000), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rubric_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['syllabus_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_id'], ['self_test_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'seq', name='uq_self_test_question_seq_per_paper')
    )
    op.create_table('self_test_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['self_test_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'student_user_id', name='uq_self_test_submission_paper_student')
    )
    op.create_table('self_test_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=8000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['self_test_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['self_test_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_self_test_answer_submission_question')
    )
    op.create_table('self_test_grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['self_test_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', name='uq_self_test_grade_submission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('self_test_grades')
    op.drop_table('self_test_answers')
    op.drop_table('self_test_submissions')
    op.drop_table('self_test_questions')
    op.drop_table('wrong_book_items')
    op.drop_table('self_test_papers')
    # ### end Alembic commands ###
